# Generated by Django 6.0.3 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/')),
                ('pin', models.CharField(default='0000', max_length=4)),
                ('xp_total', models.IntegerField(default=0)),
                ('monedas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('clases', models.ManyToManyField(related_name='alumnos', to='Misiones.clase')),
            ],
        ),
    ]
