# Generated by Django 6.0.3 on 2026-03-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Misiones.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('arduino', 'Arduino'), ('cuestionario', 'Cuestionario')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='misiones/')),
                ('codigo', models.TextField(blank=True, null=True)),
                ('link_formulario', models.URLField(blank=True, null=True)),
                ('xp_recompensa', models.IntegerField(default=50)),
                ('monedas_recompensa', models.IntegerField(default=10)),
                ('orden', models.IntegerField(default=1)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='Misiones.clase')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones', to='Misiones.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoMision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misiones.alumno')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misiones.mision')),
            ],
        ),
    ]
