# Generated by Django 6.0.3 on 2026-03-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0002_nivel_mision_progresomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresomision',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
