# Generated by Django 6.0.3 on 2026-03-18 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0003_progresomision_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo_monedas', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('requiere_validacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('entregado_usado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='Misiones.alumno')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misiones.articulotienda')),
            ],
        ),
    ]
