# Generated by Django 6.0.3 on 2026-03-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0004_articulotienda_compraalumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mision',
            name='tipo',
            field=models.CharField(choices=[('arduino', 'Arduino'), ('cuestionario', 'Cuestionario'), ('link', 'Link')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Escribe la pregunta aquí')),
                ('orden', models.IntegerField(default=1)),
                ('puntos', models.IntegerField(default=10, help_text='Puntos que otorga esta pregunta')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Misiones.mision')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Misiones.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Misiones.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Misiones.pregunta')),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_detalladas', to='Misiones.progresomision')),
            ],
        ),
    ]
