# Generated by Django 6.0.3 on 2026-03-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0005_alter_mision_tipo_pregunta_opcionrespuesta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mision',
            old_name='link_formulario',
            new_name='link',
        ),
    ]
