# Generated by Django 6.0.3 on 2026-04-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0006_rename_link_formulario_mision_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulotienda',
            name='es_avatar',
            field=models.BooleanField(default=False, help_text='Si se marca, al comprar este artículo se cambiará automáticamente el avatar del alumno.'),
        ),
    ]
