# Generated by Django 6.0.3 on 2026-04-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0007_articulotienda_es_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulotienda',
            name='es_avatar',
        ),
    ]
