# Generated by Django 6.0.3 on 2026-04-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Misiones', '0008_remove_articulotienda_es_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulotienda',
            name='tipo',
            field=models.CharField(choices=[('avatar', 'Avatar para el perfil'), ('permiso', 'Permiso / Privilegio en clase'), ('fisico', 'Recompensa Física'), ('otro', 'Otro Digital')], default='fisico', max_length=20),
        ),
    ]
